'use client';
import abzarIran from 'public/images/home/customer/abzarIran.png';
import actionaid from 'public/images/home/customer/actionaid.png';
import arvin from 'public/images/home/customer/arvin.png';
import asia from 'public/images/home/customer/asia.png';
import british from 'public/images/home/customer/british.png';
import cif from 'public/images/home/customer/cif.png';
import inanna27 from 'public/images/home/customer/inanna27.png';
import likeNative from 'public/images/home/customer/likeNative.png';
import m_mhosenpour from 'public/images/home/customer/m_mhosenpour.png';
import mshhadwather from 'public/images/home/customer/mshhadwather.png';
import muslim from 'public/images/home/customer/muslim.png';
import nehaborman from 'public/images/home/customer/nehaborman.png';
import pendi from 'public/images/home/customer/pendi.png';
import sdroa from 'public/images/home/customer/sdroa.png';
import shiftNex from 'public/images/home/customer/shiftNex.png';
import React from 'react';

import Button from '@/components/common/Button';
import CustomersLogo, {
  CustomerProps,
} from '@/components/customers/CustomersLogo';

export const initialCustomers: CustomerProps[] = [
  {
    id: 1,
    src: asia,
    alt: 'asia',
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    name: 'Ajdsaljflsadjfj',
    hoverImage: cif,
  },
  {
    id: 2,
    src: actionaid,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'actionaid',
  },
  {
    id: 3,
    src: british,
    name: 'bdlkjfldsajflk',
    alt: 'british',
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
  },
  {
    id: 4,
    src: abzarIran,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'abzarIran',
  },
  {
    id: 5,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 6,
    src: m_mhosenpour,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'm_mhosenpour',
  },
  {
    id: 7,
    src: pendi,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'pendi',
  },
  {
    id: 8,
    src: sdroa,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'sdroa',
  },
  {
    id: 9,
    src: shiftNex,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'shiftNex',
  },
  {
    id: 10,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 11,
    src: arvin,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'arvin',
  },
  {
    id: 12,
    src: nehaborman,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'nehaborman',
  },
  {
    id: 13,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 14,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 15,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 16,
    src: likeNative,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'likeNative',
  },
  {
    id: 17,
    src: inanna27,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'inanna27',
  },
  {
    id: 18,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 19,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 20,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 21,
    src: mshhadwather,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'mshhadwather',
  },
  {
    id: 22,
    src: asia,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'asia',
  },
  {
    id: 23,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 24,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 25,
    src: abzarIran,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'abzarIran',
  },
  {
    id: 26,
    src: muslim,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      'طراحی سایت -',
      'مدیریت شبکه های مجازی -',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'muslim',
  },
  {
    id: 27,
    src: asia,
    hoverImage: cif,
    titleCard: [
      'برندینگ داخل ایران -',
      '- طراحی سایت ',
      '- مدیریت شبکه های مجازی ',
    ],
    description: [
      '- SLA',
      '- Technical milestones',
      '- UI/UX',
      '- User journey',
      '- Frontend development',
      '- Backend structure design and connections',
      '- Designing',
      '- Applying gamification and branding strategies',
      '- Design and development of digital footprint',
      '- Social media management',
      '- Content creation',
      '- Maintenance',
      'لازم به ذکر است بسیاری از تمجیدها بر اساس نظرات متخصصین خود برند بوده و به اجرا رسیده.',
    ],
    name: 'A',
    alt: 'asia',
  },
  // Add more initial logos here if needed
];

export default function Customers() {
  return (
    <div className='"bg-black h-screen w-full mx-auto text-white p-8 mt-28 absolute '>
      <div className='flex justify-center items-center gap-4 mx-auto mb-8'>
        <div className='w-32 bg-[#D9D9D9] h-0.5'></div>

        <h2 className='text-center text-3xl '>Customers</h2>
        <div className='w-32 bg-[#D9D9D9] h-0.5'></div>
      </div>
      <CustomersLogo customers={initialCustomers} />
      <CustomersLogo customers={initialCustomers} />
      <CustomersLogo customers={initialCustomers} />
      <div className='flex lg:flex-row flex-col w-[80%] mx-auto justify-center items-center lg:gap-16 gap-8 p-8'>
        <h2 className='sm:font-medium font-normal sm:text-base text-center'>
          You too can join the ranks of top companies.
        </h2>
        <Button>Contact our consultant</Button>
      </div>
    </div>
  );
}
